### ISSUE TITLE
Errors on Column  'fullWidth' and on vAlign['stretch']

### ISSUE THREAD

**Issue by smooJitter** [idibidiart/react-native-responsive-grid#18]
There appears to be an issue in the source code
```
   // Column.js
   vAlign: PropTypes.oneOf(['space', 'distribute', 'middle', 'center', 'bottom', 'top']),
   fullWidtht: PropTypes.bool,
```
perhaps the following is correct,

```
   // Column.js
   vAlign: PropTypes.oneOf(['space', 'distribute', 'middle', 'center', 'bottom', 'top', 'stretch']),
   fullWidth: PropTypes.bool,
```

**Comment by idibidiart** [comment]
No, 

vAlign for Column is justifyContent which matches the PropTypes

vAlign on Row is alignItems so that can stretch children vertically!

What you're looking for is hAlign on Column which stretches children horizontally and vAlign on Row which stretches children vertically. If you put Row in Column with those settings you get stretching in both directions. I think I have to add that to the docs.

**Comment by smooJitter** [comment]
There's also this typo in Column.js, 
`fullWidtht: PropTypes.bool,`
